// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebService.DbContexts;

#nullable disable

namespace WebService.Migrations
{
    [DbContext(typeof(PayloadContext))]
    [Migration("20221207212037_RefactorInitial")]
    partial class RefactorInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("WebService.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Baz")
                        .HasColumnType("TEXT");

                    b.Property<string>("Foo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ce1fb75-d186-4700-a44a-b15382ca22ea"),
                            Baz = "bang",
                            Foo = "bar"
                        },
                        new
                        {
                            Id = new Guid("a5f0285e-8739-4b60-887d-d5b829164dd0"),
                            Baz = "whoop",
                            Foo = "big"
                        });
                });

            modelBuilder.Entity("WebService.Entities.Payload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SentFromIp")
                        .HasColumnType("TEXT");

                    b.Property<long>("TS")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("Payloads");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0411596-95f7-4553-b5bc-f90b91534506"),
                            MessageId = new Guid("1ce1fb75-d186-4700-a44a-b15382ca22ea"),
                            Priority = 2,
                            Sender = "testy-test-service",
                            SentFromIp = "1.2.3.4",
                            TS = 1530228282L
                        },
                        new
                        {
                            Id = new Guid("77194d53-0f5d-4868-bcf4-5adc693b6e62"),
                            MessageId = new Guid("a5f0285e-8739-4b60-887d-d5b829164dd0"),
                            Priority = 0,
                            Sender = "whoa very test",
                            SentFromIp = "4.3.2.1",
                            TS = 1684234873L
                        });
                });

            modelBuilder.Entity("WebService.Entities.Payload", b =>
                {
                    b.HasOne("WebService.Entities.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });
#pragma warning restore 612, 618
        }
    }
}
